/*************************************************************************
*                             -=-=-= timer.h =-=-=-
*
* THIS FILE WAS CREATED FOR ELEC4710 - REALTIME SYSTEMS
* MAJOR PROJECT ASSIGNMENT
*
* This file contains functions and definitions for the intel 8254 
* programmable interrupt timer. This timer is used to generate interrupts
* to allow us to schedule our tasks.
*
* This file maybe expanded to allow dynamic software timers to be added
* to our system
*
* Compiler: gcc
*
* Author: Colin Goudie
**************************************************************************/
#ifndef __TIMER_H__
#define __TIMER_H__

#include <os/config.h>

/**
 * This function initialises our timer and the interrupt routines ready
 * to handle our timer
 */
void init_timer(void);
/**
 * Sets the freqency of the timer in Hz
 * 
 * @param uint Frequency in HZ
 */
void set_frequency(uint frequency);

/**
 * The actual handler for a timer event generated by the 8524 interrupt
 * timer
 */
void timer_interrupt_handler(void);

#endif
